- name: Create AWS Oracle EBS EC2
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ ansible_user }}"
  roles:
    - aws_create

- name: Configure Oracle EBS Instance
  hosts: ec2_hosts # Generated group from Create AWS Instance

  pre_tasks:
    - include_vars: secrets.yml

  roles:
    - common
    - fixes
    - packages

- name: Create AMI
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ ansible_user }}"
  roles:
     - aws_create_ami
