- name: Update Redhat packages
  yum: name=* state=latest
  register: update

- debug: var=update.stdout_lines

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=320
  sudo: false
  
- name: Install epel release for RedHat
  yum: name="http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" state=present

- name: Install Pigz
  yum: name=pigz state=present

- name: Install s3cmd for S3 upload and download
  yum: name=s3cmd state=present

