
- command: cp {{ workspace }}/jenkins_dynamic_inventory.template {{ workspace }}/jenkins_dynamic_inventory creates='{{ workspace }}/jenkins_dynamic_inventory'

- block:
    - debug: msg="Replace db type token"
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###db_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###db_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  # Repeat if it failed. Fix for known error file not found.
  rescue:
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###db_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###db_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  when: type == "db"
  
- block:
    - debug: msg="Replace app1 type token"
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app1_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app1_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  # Repeat if it failed. Fix for known error file not found.
  rescue:
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app1_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app1_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  when: type == "app1"

- block:
    - debug: msg="Replace app2 type token"
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app2_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app2_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  # Repeat if it failed. Fix for known error file not found.
  rescue:
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app2_host###' replace={{ custom_hostname }}
    - replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###app2_ip###' replace={{ ec2["instances"][0]["private_ip"] }}

  when: type == "app2"

- replace: dest={{ workspace }}/jenkins_dynamic_inventory regexp='###env###' replace={{ env }}

