---
- block:
  - name: Provision oracle ebs instance
    ec2:
      key_name: "{{ key_name }}" 
      group_id: "{{ security_group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      wait_timeout: 500
      volumes:
       - device_name: "{{ volume_device_name }}"
         volume_type: "{{ volume_type }}"
         volume_size: "{{ volume_size }}"
         delete_on_termination: True
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: "{{ assign_public_ip }}"
      count: 1
      instance_tags:
         Name: "{{ instance_name }}"
      region: "{{ aws_region }}"
    register: ec2

  - debug: var=ec2

  rescue:
  - debug: msg="Instance creation failed due to the error above. Please also ensure that EC2_ACCESS_KEY and EC2_SECRET_KEY environment variables are defined"
  - fail: 
    when: "ec2.rc != 0"

- name: Write the instance id to a file
  shell: echo "{{ ec2.instance_ids }}" | tr -d "[]u'" > ./instance_ids.txt

- name: save IP to inventory file to a folder 1 level below
  copy: content={{ ec2["instances"][0]["private_ip"] }} dest={{ workspace }}/{{ instance_name }}.ip

- name: Wait for SSH to come up
  wait_for: host={{ ec2["instances"][0]["private_ip"] }} port=22 delay=60 timeout=320 state=started

- name: Add IP to ec2_hosts group
  add_host: hostname={{ ec2["instances"][0]["private_ip"] }} groups=ec2_hosts
